(()=>{
const GATEWAY='https://master-ai-avito.vercel.app';
let leads=[],selected='',messages=[],pollTimer=0;
const okRole=()=>['owner','dispatcher_logistic','logistic'].includes(window.MasterAICloud?.profile?.role||'');
const h=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=t=>{const d=new Date((Number(t)||Date.parse(t)||Date.now())*(Number(t)<2e10?1000:1));return d.toLocaleString('ru-RU',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})};
async function api(path,opt={}){const token=await window.MasterAICloud?.getIdToken?.();if(!token)throw new Error('Войдите в аккаунт');const r=await fetch(GATEWAY+path,{...opt,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json',...(opt.headers||{})}});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.message||'Ошибка связи '+r.status);return j}
function shell(){if(document.getElementById('avitoLeadBtn'))return;const st=document.createElement('style');st.textContent=`.avito-lead-btn{position:fixed;right:22px;bottom:88px;z-index:8000;border:0;border-radius:18px;padding:13px 17px;background:linear-gradient(135deg,#1677ff,#6d5dfc);color:#fff;font:700 14px Arial,sans-serif;box-shadow:0 16px 40px #071a3d66;cursor:pointer}.avito-lead-count{display:inline-grid;place-items:center;min-width:22px;height:22px;margin-left:8px;padding:0 6px;border-radius:99px;background:#fff;color:#155bd7}.avito-drawer{position:fixed;inset:0;z-index:9000;background:#07122599;backdrop-filter:blur(8px);display:none;align-items:stretch;justify-content:flex-end}.avito-drawer.open{display:flex}.avito-panel{width:min(1100px,96vw);height:100%;background:#f5f8fd;color:#13233d;display:grid;grid-template-columns:340px 1fr;box-shadow:-24px 0 70px #0005}.avito-side{border-right:1px solid #dce5f2;overflow:auto;background:#fff}.avito-head{position:sticky;top:0;z-index:2;padding:18px;background:#fff;border-bottom:1px solid #e5ebf4}.avito-head h2{margin:0;font:800 21px Arial}.avito-head p{margin:5px 0 0;color:#65758d;font:13px Arial}.avito-list{padding:10px}.avito-card{width:100%;text-align:left;border:1px solid #e0e7f2;background:#fff;border-radius:14px;padding:13px;margin:0 0 8px;cursor:pointer;font:14px Arial}.avito-card.active{border-color:#2b74e8;box-shadow:0 0 0 3px #2b74e818}.avito-card b{display:block;margin-bottom:6px}.avito-card small{color:#73819a}.avito-main{display:flex;flex-direction:column;min-width:0}.avito-toolbar{padding:16px 20px;background:#fff;border-bottom:1px solid #e0e7f2;display:flex;gap:8px;align-items:center;flex-wrap:wrap}.avito-toolbar select,.avito-toolbar button,.avito-compose textarea{font:14px Arial;border:1px solid #cbd7e7;border-radius:10px;padding:10px;background:#fff}.avito-close{margin-left:auto}.avito-chat{flex:1;overflow:auto;padding:22px;display:flex;flex-direction:column;gap:10px}.avito-msg{max-width:76%;padding:11px 13px;border-radius:14px;background:#fff;box-shadow:0 4px 14px #18345b0d;font:14px/1.45 Arial}.avito-msg.out{align-self:flex-end;background:#dceaff}.avito-msg time{display:block;margin-top:4px;color:#748197;font-size:11px}.avito-compose{display:flex;gap:10px;padding:15px 20px;background:#fff;border-top:1px solid #e0e7f2}.avito-compose textarea{flex:1;resize:none}.avito-primary{background:#1769e0!important;color:#fff!important;border-color:#1769e0!important;font-weight:700!important}@media(max-width:720px){.avito-lead-btn{right:12px;bottom:78px}.avito-panel{width:100vw;grid-template-columns:1fr}.avito-side{max-height:38vh}.avito-main{min-height:62vh}.avito-msg{max-width:88%}}`;document.head.appendChild(st);
const b=document.createElement('button');b.id='avitoLeadBtn';b.className='avito-lead-btn';b.innerHTML='💬 Лиды Avito <span class="avito-lead-count" id="avitoLeadCount">0</span>';b.onclick=()=>{document.getElementById('avitoDrawer').classList.add('open');render();pull()};document.body.appendChild(b);
const d=document.createElement('div');d.id='avitoDrawer';d.className='avito-drawer';d.innerHTML=`<section class="avito-panel"><aside class="avito-side"><div class="avito-head"><h2>Лиды Avito</h2><p>Сообщения и звонки создаются автоматически</p></div><div class="avito-list" id="avitoList"></div></aside><main class="avito-main"><div class="avito-toolbar"><select id="avitoStage"><option value="new">Новый</option><option value="think">Подумать</option><option value="order">Заказ</option><option value="refused">Отказ</option></select><select id="avitoMaster"><option value="">Мастер не назначен</option></select><button id="avitoConvert" class="avito-primary">Оформить заказ</button><button id="avitoRefresh">Обновить</button><button class="avito-close" id="avitoClose">Закрыть</button></div><div class="avito-chat" id="avitoChat"><div style="margin:auto;color:#718096">Выберите лид</div></div><div class="avito-compose"><textarea id="avitoText" rows="2" placeholder="Напишите клиенту…"></textarea><button id="avitoSend" class="avito-primary">Отправить</button></div></main></section>`;document.body.appendChild(d);
d.onclick=e=>{if(e.target===d)d.classList.remove('open')};document.getElementById('avitoClose').onclick=()=>d.classList.remove('open');document.getElementById('avitoRefresh').onclick=pull;document.getElementById('avitoStage').onchange=saveMeta;document.getElementById('avitoMaster').onchange=saveMeta;document.getElementById('avitoSend').onclick=send;document.getElementById('avitoText').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}};document.getElementById('avitoConvert').onclick=convert;
}
function render(){const count=leads.filter(x=>x.stage==='new'||!x.stage).length;const badge=document.getElementById('avitoLeadCount');if(badge)badge.textContent=count;const list=document.getElementById('avitoList');if(!list)return;list.innerHTML=leads.map(x=>`<button class="avito-card ${x.id===selected?'active':''}" data-lead="${h(x.id)}"><b>${x.kind==='call'?'☎️':'💬'} ${h(x.title||'Лид Avito')}</b><div>${h(x.preview||x.phone||'Новый контакт')}</div><small>${h(x.stageLabel||({new:'Новый',think:'Подумать',order:'Заказ',refused:'Отказ'}[x.stage]||'Новый'))} · ${fmt(x.createdAt)}</small></button>`).join('')||'<div style="padding:20px;color:#718096">Новых обращений нет</div>';list.querySelectorAll('[data-lead]').forEach(b=>b.onclick=()=>openLead(b.dataset.lead));if(selected){const x=leads.find(y=>y.id===selected);if(x){document.getElementById('avitoStage').value=x.stage||'new';const sel=document.getElementById('avitoMaster'),names=(window.MasterAIMasters?.()||[]);sel.innerHTML='<option value="">Мастер не назначен</option>'+names.map(n=>`<option ${n===x.master?'selected':''}>${h(n)}</option>`).join('')}}}
async function openLead(id){selected=id;render();const x=leads.find(y=>y.id===id);const chat=document.getElementById('avitoChat');if(x?.kind!=='message'){chat.innerHTML=`<div class="avito-msg">Входящий звонок${x.phone?' · '+h(x.phone):''}<time>${fmt(x.createdAt)}</time></div>`;return}chat.innerHTML='<div style="margin:auto;color:#718096">Загрузка переписки…</div>';try{messages=(await api('/api/messages?chatId='+encodeURIComponent(x.externalId))).messages||[];chat.innerHTML=messages.map(m=>`<div class="avito-msg ${m.direction==='out'?'out':''}">${h(m.text||'[вложение]')}<time>${fmt(m.created)}</time></div>`).join('')||'<div style="margin:auto;color:#718096">Переписка пока пуста</div>';chat.scrollTop=chat.scrollHeight}catch(e){chat.innerHTML=`<div style="margin:auto;color:#b42318">${h(e.message)}</div>`}}
async function saveMeta(){const x=leads.find(y=>y.id===selected);if(!x)return;x.stage=document.getElementById('avitoStage').value;x.master=document.getElementById('avitoMaster').value;await window.MasterAICloud.saveAvitoLead(x);render()}
async function send(){const x=leads.find(y=>y.id===selected),ta=document.getElementById('avitoText'),text=ta.value.trim();if(!x||x.kind!=='message'||!text)return;const btn=document.getElementById('avitoSend');btn.disabled=true;try{await api('/api/send',{method:'POST',body:JSON.stringify({chatId:x.externalId,text})});ta.value='';x.preview=text;x.stage=x.stage||'new';await window.MasterAICloud.saveAvitoLead(x);await openLead(x.id)}catch(e){alert('Не удалось отправить: '+e.message)}finally{btn.disabled=false}}
function convert(){const x=leads.find(y=>y.id===selected);if(!x)return;document.getElementById('avitoDrawer').classList.remove('open');if(typeof window.MasterAIOrderFromLead!=='function')return;window.MasterAIOrderFromLead(x);x.stage='order';window.MasterAICloud.saveAvitoLead(x);}
async function pull(){if(!okRole())return;try{const j=await api('/api/pull?since='+encodeURIComponent(new Date(Date.now()-7*864e5).toISOString()));for(const raw of [...(j.calls||[]),...(j.chats||[])]){const id=raw.id.replace(/[^A-Za-z0-9_-]/g,'-');const old=leads.find(x=>x.id===id);await window.MasterAICloud.saveAvitoLead({...raw,id,stage:old?.stage||'new',master:old?.master||'',createdAt:raw.createdAt||new Date().toISOString(),preview:raw.preview||old?.preview||''})}}catch(e){console.warn('Avito pull',e)}}
async function boot(){shell();for(let i=0;i<60&&!window.MasterAICloud?.profile;i++)await new Promise(r=>setTimeout(r,250));if(!okRole()){document.getElementById('avitoLeadBtn')?.remove();return}window.MasterAICloud.subscribeAvitoLeads?.(x=>{leads=x;render()});await pull();pollTimer=setInterval(pull,60000)}
window.addEventListener('load',()=>setTimeout(boot,300));
})();

